TABLE_(COLUMNS)
   INT_     (COLID) PRIMARY_KEY
   STRING_  (COLNAME, 200) 
   STRING_  (SRCCOLCODE, 200)
   STRING_  (SRCDATATYPCODE, 10)
   INT_     (SRCDATATYPWDTH)
   INT_     (SRCDATATYPDEC)
   INT_     (SRCDATAFFSTARTPOS)
   INT_     (SRCDATAFFFINPOS)
   INT_     (TBID)
   INT_     (PHYSORD)
   INT_     (BESTFITWDTH)
   STRING_  (NOTE, 1000)
   BOOL_    (EXPWRAPINQUOTES)
END_TABLE

TABLE_(TABLES)
   INT      (TBID) PRIMARY_KEY
   STRING_  (TBNAME, 200) 
   STRING_  (TBADDRESS, 200)
   STRING   (NOTE, 1000)
END_TABLE

TABLE_(TASKS)
   INT_     (TASKID) PRIMARY_KEY
   STRING_  (TASKNAME, 100)
   STRING_  (SRCCODE, 100)
   STRING   (NOTE, 1000)
   STRING_  (ASSIGNEDBYWHO, 100)
   STRING_  (PROJECTNAME, 100)
   INT_     (PRIORITYWITHINPROJECT)
   STRING_  (WHY, 300)
END_TABLE

TABLE_(PROJECTS)
   INT_     (PROJECTID) PRIMARY_KEY
   STRING   (PROJECTNAME, 100)
   STRING   (NOTE, 1000)
   STRING_  (MASTERPROJECTNAME, 100)
END_TABLE

TABLE_(SCRIPTS)
   INT_     (SCRIPTID) PRIMARY_KEY
   STRING_  (SCRIPTNAME, 100)
   STRING_  (SCRIPT, 1000)
   STRING   (NOTE, 1000)
END_TABLE

TABLE_(TASKS_R)
   INT_     (RELID) PRIMARY_KEY
   INT      (TASKID)
   STRING   (TASKNAME, 100)
   STRING   (SRCCODE, 100)
   STRING_  (TASKNOTE, 1000)
   STRING_  (SCRIPTNOTE, 1000)
   STRING   (ASSIGNEDBYWHO, 100)
   STRING   (PROJECTNAME, 100)
   INT      (PRIORITYWITHINPROJECT)
   INT      (SCRIPTID)
   INT      (SCRIPT)
   STRING   (WHY, 300)
   INT_     (RELCONNID)
   STRING_  (RELCONNNAME, 200)
   TIME_    (ADDTIMESTAMP)
   INT_     (SCRIPTTARGET)
   STRING_  (TARGETNAME, 200)
   STRING_  (FASTFLUSHTARGET, 10)
   INT_     (ROWLIMIT)
   INT_     (PROCESSORDER)
END_TABLE

TABLE_(CONTACTS)
   INT_     (CONTACTID) PRIMARY_KEY
   STRING_  (CONTACTNAME, 100)
   STRING_  (EMAILADDRESS, 100)
   STRING_  (HOMEPHONENO, 50)
   STRING_  (WORKPHONENO, 50)
   STRING_  (CELLPHONENO, 50)
   STRING_  (NONWORKEMAILADDRESS, 100)
   STRING   (NOTE, 1000)
END_TABLE
