TABLE_(COLUMNS)
   INT_     (COLID) PRIMARY_KEY
   STRING_  (COLNAME, 200) 
   STRING_  (SRCCOLCODE, 200)
   STRING_  (SRCDATATYPCODE, 10)
   INT_     (SRCDATATYPWDTH)
   INT_     (SRCDATATYPDEC)
   INT_     (SRCDATAFFSTARTPOS)
   INT_     (SRCDATAFFFINPOS)
   INT_     (TBID)
   INT_     (PHYSORD)
   INT_     (BESTFITWDTH)
   STRING_  (NOTE, 1000)
   BOOL_    (EXPWRAPINQUOTES)
END_TABLE

TABLE_(TABLES)
   INT      (TBID) PRIMARY_KEY
   STRING_  (TBNAME, 200) 
   STRING_  (TBADDRESS, 200)
   STRING   (NOTE, 1000)
END_TABLE

TABLE_(TASKS)
   INT_     (TASKID) PRIMARY_KEY
   STRING_  (TASKNAME, 100)
   STRING_  (SRCCODE, 100)
   STRING   (NOTE, 1000)
   STRING_  (ASSIGNEDBYWHO, 100)
   STRING_  (PROJECTNAME, 100)
   INT_     (PRIORITYWITHINPROJECT)
END_TABLE

TABLE_(PROJECTS)
   INT_     (PROJECTID) PRIMARY_KEY
   STRING   (PROJECTNAME, 100)
   STRING   (NOTE, 1000)
   STRING_  (MASTERPROJECTNAME, 100)
END_TABLE

TABLE_(SCRIPTS)
   INT_     (SCRIPTID) PRIMARY_KEY
   STRING_  (SCRIPTNAME, 100)
   STRING_  (SCRIPT, 1000)
   STRING   (NOTE, 1000)
END_TABLE

